### ISSUE TITLE
hash buff size enough?

### ISSUE THREAD

**Issue by mtxrym** [yhirose/cpp-fstlib#7]
hash function use a buffer 1024， is it enough for large of data

**Comment by yhirose** [comment]
@mtxrym, so far, I don't experience any major hash collision with my test data files. Please let me know if you discover a problem.

**Comment by mtxrym** [comment]
it's not about hash collision; transitions size is larger than 1024,  buff is not large enough, segment fault
![image](https://user-images.githubusercontent.com/5978133/97451387-a9c09680-196e-11eb-856d-f82955b62618.png)

**Comment by yhirose** [comment]
@mtxrym, thanks for more detailed information. Fortunately, the transition size never goes beyond 256, because `arc` is `char` and the transitions cannot have the same arc entry more than once in fst structure.

But `buff` also includes `id` (`uint32`) and `output` (value size depends on `output_t`) and `state_output` (same as `output`). So it might exceed 1024 when transitions contain many arcs with long string output though, it's a rare case.
Just in case it happens, I'll make a change to throw an exception when data exceeds the buff size.

Did you really experience that situation? If so, what kind of data did you use? Thanks!

**Comment by mtxrym** [comment]
just terms with averge 30~40bytes , largest 100 bytes(with chinese character), 400w together to compile, it encounters coredump with buf_len is 1058, exceed 1024

**Comment by yhirose** [comment]
What does it mean by `400w together to compile`? Also in your case, how much buffer size is needed?

**Comment by mtxrym** [comment]
it seems 2048 is enough；
fst::compile<uint32_t>(items, m_term_str, true)
items is vector size ablout 400w

**Comment by yhirose** [comment]
@mtxrym, thanks for the more information. I'll make a necessary change to fix it soon. Thanks!

**Comment by yhirose** [comment]
@mtxrym, the current master doesn't have this bug anymore. Thanks for your contribution!
